server:
  port: 13001
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
logging:
  level:
    org.springdoc: DEBUG
    org.springframework: DEBUG

spring:
  devtools:
    restart:
      enabled: false
  application:
    name: manual-service
#  security:
#    enabled: false
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        cache.use_second_level_cache: false
        cache.use_query_cache: false

  datasource: #mysql_container #localhost
    url: ${DB_URL}
    username: ${DB_USERNAME} #${DB_USERNAME}
    password: ${DB_PASSWORD} #${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: HikariCP
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 20000
      connection-test-query: SELECT 1
      leak-detection-threshold: 60000
aws:
  region: ap-northeast-2
  s3:
    bucket-name: epicode
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVER}
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
#  cache:
#    type: redis
#    data:
#      redis:
#        host: my-redis #localhost #컨테이너 이름
#        port: 6379
#        password: "0000"
#        database: 0
#        timeout: 2000ms
#        time-to-live:
#          crawledEduContents: 600s # 10분
#        lettuce:
#          pool:
#            max-size: 8
#            max-idle: 8
#            min-idle: 0
#          shutdown-timeout: 100
#
#  logging:
#    level:
#      root: INFO
#      org.springframework: DEBUG
#      org.hibernate.SQL: DEBUG
#      org.hibernate.type.descriptor.sql: TRACE
#      org.springframework.data.redis: TRACE
#      org.springframework.cache: DEBUG       # Spring Cache 관련 로그
#      org.springframework.cache.redis: DEBUG # Redis 캐시 관련 로그
#    file:
#      name: logs/application.log