version: '3.8'

services:

  discovery-service:
    container_name: discovery-service
    image: discovery-service
    ports:
      - "18761:18761"
    networks:
      - app-network

  apigateway-service:
    image: apigateway-service
    ports:
      - "11000:11000"
    environment:
      EUREKA_SERVER: ${EUREKA_SERVER}
      JWT_KEY: ${JWT_KEY}
    networks:
      - app-network
    depends_on:
      - discovery-service


  calendar-service:
    image: calendar-service
    ports:
      - "13002:13002"
    environment:
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_URL: ${DB_URL}
      EUREKA_SERVER: ${EUREKA_SERVER}
    networks:
      - app-network
    depends_on:
      - discovery-service
      - apigateway-service
      
  branch-service:
    image: branch-service
    ports:
      - "13003:13003"
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_URL: ${DB_URL}
      EUREKA_SERVER: ${EUREKA_SERVER}
      JWT_KEY: ${JWT_KEY}
    networks:
      - app-network
    depends_on:
      - discovery-service
      - apigateway-service

  manual-service:
    image: manual-service
    ports:
      - "13001:13001"
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_URL: ${DB_URL}
      EUREKA_SERVER: ${EUREKA_SERVER}
      EPI_SERVER: ${EPI_SERVER}
    networks:
      - app-network
    depends_on:
      - discovery-service
      - apigateway-service
      - branch-service

  user-service:
    image: user-service
    ports:
      - "13004:13004"
    environment:
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_URL: ${DB_URL}
      EUREKA_SERVER: ${EUREKA_SERVER}
      KAKAO_RESTAPI: ${KAKAO_RESTAPI}
      BASE_URL: ${BASE_URL}
      JWT_KEY: ${JWT_KEY}
      
    networks:
      - app-network
    depends_on:
      - discovery-service
      - apigateway-service
      

  kafka:
    image: bitnami/kafka:4.0.0
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_KRAFT_CLUSTER_ID: epicode-cluster-01
      KAFKA_CFG_NODE_ID: 1
      KAFKA_CFG_PROCESS_ROLES: broker,controller
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_LOG_DIRS: /bitnami/kafka/data
    volumes:
      - kafka_data:/bitnami/kafka
    networks:
      - app-network

  approval-service:
    image: approval-service
    ports:
      - "13005:13005"
    environment:
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_URL: ${DB_URL}
      EUREKA_SERVER: ${EUREKA_SERVER}
      BASE_URL: ${BASE_URL}
      JWT_KEY: ${JWT_KEY}

    networks:
      - app-network
    depends_on:
      - discovery-service
      - apigateway-service
      
  salary-service:
    image: salary-service
    ports:
      - "13006:13006"
    environment:
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_URL: ${DB_URL}
      EUREKA_SERVER: ${EUREKA_SERVER}
      JWT_KEY: ${JWT_KEY}
      SPRING_KAFKA_BOOTSTRAP_SERVERS: ${SPRING_KAFKA_BOOTSTRAP_SERVERS}
      
    networks:
      - app-network
    depends_on:
      - discovery-service
      - apigateway-service
      - user-service


networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
  kafka_data:
