version: '3.8'

services:

  discovery-service:
    image: discovery-service
    ports:
      - "18761:18761"
    networks:
      - app-network

  apigateway-service:
    image: apigateway-service
    ports:
      - "11000:11000"
    environment:
      EUREKA_SERVER: ${EUREKA_SERVER}
      JWT_KEY: ${JWT_KEY}
    networks:
      - app-network
    depends_on:
      - discovery-service

  manual-service:
    image: manual-service
    ports:
      - "13001:13001"
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_URL: ${DB_URL}
      EUREKA_SERVER: ${EUREKA_SERVER}
      EPI_SERVER: ${EPI_SERVER}
    networks:
      - app-network
    depends_on:
      - discovery-service
      - apigateway-service

  calendar-service:
    image: calendar-service
    ports:
      - "13002:13002"
    environment:
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_URL: ${DB_URL}
      EUREKA_SERVER: ${EUREKA_SERVER}
    networks:
      - app-network
    depends_on:
      - discovery-service
      - apigateway-service
      
  branch-service:
    image: branch-service
    ports:
      - "13003:13003"
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_URL: ${DB_URL}
      EUREKA_SERVER: ${EUREKA_SERVER}
      JWT_KEY: ${JWT_KEY}
    networks:
      - app-network
    depends_on:
      - discovery-service
      - apigateway-service

  user-service:
    image: user-service
    ports:
      - "13004:13004"
    environment:
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_URL: ${DB_URL}
      EUREKA_SERVER: ${EUREKA_SERVER}
      KAKAO_RESTAPI: ${KAKAO_RESTAPI}
      BASE_URL: ${BASE_URL}
      JWT_KEY: ${JWT_KEY}
      
    networks:
      - app-network
    depends_on:
      - discovery-service
      - apigateway-service
      
  user-service-2:
    image: user-service
    ports:
      - "23004:13004"
    environment:
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_URL: ${DB_URL}
      EUREKA_SERVER: ${EUREKA_SERVER}
      KAKAO_RESTAPI: ${KAKAO_RESTAPI}
      BASE_URL: ${BASE_URL}
      JWT_KEY: ${JWT_KEY}
      
    networks:
      - app-network
    depends_on:
      - discovery-service
      - apigateway-service


networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
