version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD} # MySQL root 비밀번호
      MYSQL_DATABASE: "manual_db" # 생성할 데이터베이스 이름
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

  discovery-service:
    image: discovery-service
    ports:
      - "18761:18761"
    networks:
      - app-network
    depends_on:
      - mysql

  apigateway-service:
    image: apigateway-service
    ports:
      - "11000:11000"
    networks:
      - app-network
    depends_on:
      - discovery-service
      - mysql

  manual-service:
    image: manual-service
    ports:
      - "13001:13001"
    environment:
      DB_USERNAME: ${DB_USERANAME}
      DB_PASSWORD: ${DB_PASSWORD}
    networks:
      - app-network
    depends_on:
      - discovery-service
      - apigateway-service
      - mysql

  calendar-service:
    image: manual-service
    ports:
      - "13002:13002"
    environment:
      DB_USERNAME: ${DB_USERANAME}
      DB_PASSWORD: ${DB_PASSWORD}
    networks:
      - app-network
    depends_on:
      - discovery-service
      - apigateway-service
      - mysql

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
