name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Create .env file for build
        run: |
          echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "EUREKA_SERVER=${{ secrets.EUREKA_SERVER }}" >> .env
          echo "DB_URL=${{ secrets.DB_URL }}" >> .env
          echo "KAKAO_RESTAPI=${{ secrets.KAKAO_RESTAPI }}" >> .env
          echo "BASE_URL=${{ secrets.BASE_URL }}" >> .env
          echo "JWT_KEY=${{ secrets.JWT_KEY }}" >> .env

      - name: Build manual-service
        working-directory: manual-service
        env:
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          EUREKA_SERVER: ${{ secrets.EUREKA_SERVER }}
          DB_URL: ${{ secrets.DB_URL }}
          KAKAO_RESTAPI: ${{ secrets.KAKAO_RESTAPI }}
          BASE_URL: ${{ secrets.BASE_URL }}
          JWT_KEY: ${{ secrets.JWT_KEY }}
        run: ./gradlew clean build -x test

      - name: Build apigateway-service
        working-directory: apigateway-service
        env:
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          EUREKA_SERVER: ${{ secrets.EUREKA_SERVER }}
          DB_URL: ${{ secrets.DB_URL }}
          KAKAO_RESTAPI: ${{ secrets.KAKAO_RESTAPI }}
          BASE_URL: ${{ secrets.BASE_URL }}
          JWT_KEY: ${{ secrets.JWT_KEY }}
        run: |
          chmod +x mvnw
          ./mvnw clean compile package

      - name: Build discovery-service
        working-directory: discovery-service
        env:
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: |
          chmod +x mvnw
          ./mvnw clean compile package
          
      - name: Build calendar-service
        working-directory: calendar-service
        env:
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          EUREKA_SERVER: ${{ secrets.EUREKA_SERVER }}
          DB_URL: ${{ secrets.DB_URL }}
        run: ./gradlew clean build -x test
        
      - name: Build user-service
        working-directory: user-service
        env:
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          EUREKA_SERVER: ${{ secrets.EUREKA_SERVER }}
          DB_URL: ${{ secrets.DB_URL }}
          KAKAO_RESTAPI: ${{ secrets.KAKAO_RESTAPI }}
          BASE_URL: ${{ secrets.BASE_URL }}
          JWT_KEY: ${{ secrets.JWT_KEY }}
        run: ./gradlew clean build -x test

      - name: Build branch-service
        working-directory: branch-service
        env:
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          EUREKA_SERVER: ${{ secrets.EUREKA_SERVER }}
          DB_URL: ${{ secrets.DB_URL }}
        run: ./gradlew clean build -x test

      - name: Build Docker images
        run: |
          docker build -t manual-service:latest ./manual-service
          docker build -t apigateway-service:latest ./apigateway-service
          docker build -t discovery-service:latest ./discovery-service
          docker build -t calendar-service:latest ./calendar-service
          docker build -t user-service:latest ./user-service
          docker build -t branch-service:latest ./branch-service

      - name: Save Docker images to files
        run: |
          docker save manual-service:latest -o manual-service.tar
          docker save apigateway-service:latest -o apigateway-service.tar
          docker save discovery-service:latest -o discovery-service.tar
          docker save calendar-service:latest -o calendar-service.tar
          docker save user-service:latest -o user-service.tar
          docker save branch-service:latest -o branch-service.tar
          
      - name: Verify .tar files
        run: |
          ls -lh ./*.tar
      
      - name: Deploy to EC2
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          # Save the private key
          echo "${{ secrets.PRIVATE_KEY }}" > epicode_key.pem
          chmod 600 epicode_key.pem

          # Copy Docker images, compose file, and .env to EC2
          scp -i epicode_key.pem -o StrictHostKeyChecking=no manual-service.tar ubuntu@${{ secrets.EC2_IP }}:/home/ubuntu/deploy/
          scp -i epicode_key.pem -o StrictHostKeyChecking=no apigateway-service.tar ubuntu@${{ secrets.EC2_IP }}:/home/ubuntu/deploy/
          scp -i epicode_key.pem -o StrictHostKeyChecking=no discovery-service.tar ubuntu@${{ secrets.EC2_IP }}:/home/ubuntu/deploy/
          scp -i epicode_key.pem -o StrictHostKeyChecking=no calendar-service.tar ubuntu@${{ secrets.EC2_IP }}:/home/ubuntu/deploy/
          scp -i epicode_key.pem -o StrictHostKeyChecking=no user-service.tar ubuntu@${{ secrets.EC2_IP }}:/home/ubuntu/deploy/
          scp -i epicode_key.pem -o StrictHostKeyChecking=no branch-service.tar ubuntu@${{ secrets.EC2_IP }}:/home/ubuntu/deploy/
          scp -i epicode_key.pem -o StrictHostKeyChecking=no docker-compose.yml ubuntu@${{ secrets.EC2_IP }}:/home/ubuntu/deploy/
          scp -i epicode_key.pem -o StrictHostKeyChecking=no .env ubuntu@${{ secrets.EC2_IP }}:/home/ubuntu/deploy/

          # Deploy with Docker Compose
          ssh -i epicode_key.pem -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_IP }} << EOF
            cd /home/ubuntu/deploy
            docker load -i manual-service.tar
            docker load -i apigateway-service.tar
            docker load -i discovery-service.tar
            docker load -i calendar-service.tar
            docker load -i user-service.tar
            docker load -i branch-service.tar
            docker-compose down || true
            docker-compose up -d
          EOF
