server:
  port: 11000

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:18761/eureka

spring:
  application:
    name: apigateway-service
  cloud:
    gateway:
      routes:
        - id: manual-service
          uri: http://localhost:13001/
          predicates:
            - Path=/api/manuals/**
#            filters:
#              - AddRequestHeader=first-request, first-requests-header2
#              - AddResponseHeader=first-response, first-response-header2