server:
  shutdown: immediate
  port: 11000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVER} #http://localhost:18761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}

spring:
  devtools:
    restart:
      enabled: false
  jmx:
    enabled: false
  application:
    admin:
      enabled: false
    name: apigateway-service
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"       # 모든 도메인 허용
            allowedMethods: "*"       # 모든 HTTP 메서드 허용 (GET, POST, PUT, DELETE 등)
            allowedHeaders: "*"       # 모든 헤더 허용
#      default-filters:
#        - name: GlobalFilter
#          args:
#            baseMessage: Spring Cloud Gateway Global Filter
#            preLogger: true
#            postLogger: true
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/auth/**
            
        - id: web-user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/web/auth/**

        - id: salaries-service
          uri: lb://SALARY-SERVICE
          predicates:
            - Path=/api/salaries/**
          filters:
            - JwtAuthenticationFilter

        - id: user-service-profile
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/profile/**
          filters:
            - JwtAuthenticationFilter

        - id: branch-service
          uri: lb://BRANCH-SERVICE
          predicates:
            - Path=/api/branch/**
          filters:
            - JwtAuthenticationFilter

        - id: branch-service-invite
          uri: lb://BRANCH-SERVICE
          predicates:
            - Path=/api/branch/invite/**
          filters:
            - InviteJwtAuthenticationFilter

        - id: manual-service
          uri: lb://MANUAL-SERVICE
          predicates:
            - Path=/api/manuals/**
          filters:
            - JwtAuthenticationFilter

        - id: calendar-service
          uri: lb://CALENDAR-SERVICE
          predicates:
            - Path=/api/calendar/**
          filters:
            - JwtAuthenticationFilter
jwt:
  secret-key: ${JWT_KEY}

logging:
  level:
    org.springframework.cloud.gateway: DEBUG

